package com.tgb.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.tgb.ws.HelloWorld;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T15:09:36.791+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "HelloWorldWs", 
                  wsdlLocation = "http://localhost:9002/crazyit?wsdl",
                  targetNamespace = "http://impl.ws.tgb.com/") 
public class HelloWorldWs extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.tgb.com/", "HelloWorldWs");
    public final static QName HelloWorldWsPort = new QName("http://impl.ws.tgb.com/", "HelloWorldWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9002/crazyit?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldWs.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9002/crazyit?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldWs(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWs() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorldWs(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldWs(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldWs(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public HelloWorld getHelloWorldWsPort() {
        return super.getPort(HelloWorldWsPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public HelloWorld getHelloWorldWsPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWsPort, HelloWorld.class, features);
    }

}
