package com.tgb.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T15:09:36.745+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://ws.tgb.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://ws.tgb.com/HelloWorld/sayHiRequest", output = "http://ws.tgb.com/HelloWorld/sayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.tgb.com/", className = "com.tgb.ws.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.tgb.com/", className = "com.tgb.ws.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
